LP1852782 Vandelay MARC editor module repair
With the addition of Fast Add item support, the MARC editor requires
access to the HoldingsModule, which was not importe directly into
Vandelay, unlike the catalog.  This patch tells the MARC editor to
import the module itself.

Fixes:

QueuedRecordComponent.html:22
NullInjectorError: StaticInjectorError(BaseModule)[MarcEditorComponent
-> HoldingsService]:
  StaticInjectorError(Platform: core)[MarcEditorComponent ->
  HoldingsService]:
      NullInjectorError: No provider for HoldingsService!

Signed-off-by: Bill Erickson <berickxx@gmail.com>

Signed-off-by: Jane Sandberg <sandbej@linnbenton.edu>