LP1759864: Mark Item Damaged from Holdings View Fails
"Mark Item Damaged" fails on the holdings view and from the patron profile holds tab.

the javascript console indicates a dependency issue:
Error: [$injector:unpr] Unknown provider: egItemProvider <- egItem

egItem is defined in web/js/ui/default/staff/circ/services/item.js

resolved by including the item.js source in the index.tt2 template files for both screens.

Signed-off-by: a. bellenir <abelleni@grpl.org>
Signed-off-by: Remington Steed <rjs7@calvin.edu>
Signed-off-by: Bill Erickson <berickxx@gmail.com>