LP1830973 Angular 8 org family test spec repair
The test runner does not like that the test expectations are wrapped in
the fixture.whenStable promise.  It reports an error, since no
expectations occur in line with the test:

ERROR: 'Spec 'Component: OrgFamilySelect allows user to turn off
includeDescendants checkbox' has no expectations.'

As the whenStable checks do not appear to be necessary, simply removing
them resolves the issue and allows the tests to succeed.

Signed-off-by: Bill Erickson <berickxx@gmail.com>
Signed-off-by: Jason Etheridge <jason@EquinoxInitiative.org>