LP#1676608: allow focus-me to accept constant
A handfull of cases have arisen, including but not limited to
the copy alerts feature, where focus-me is set to simply "true"
rather than being bound to to a scope variable. This patch formalizes
this and gets rid of the following console warning:

angular.min.js:119 TypeError: model.assign is not a function
    at ui.js:23
    at angular.min.js:160
    at f (angular.min.js:45)
    at angular.min.js:48
(anonymous) @ angular.min.js:119

Signed-off-by: Galen Charlton <gmc@equinoxinitiative.org>
Signed-off-by: Mike Rylander <mrylander@gmail.com>