LP#1677416: unbreak use of egOrgSelector by egEditFmRecord
This patch fixes a regression where attempting to change
the value of an egOrgSelector embedded in an egEditFmRecord
would result in errors like this:

Error: [$compile:nonassign] http://errors.angularjs.org/1.5.11/$compile/nonassign?p0=rec_orgs%5Bfield.name%5D()&p1=selected&p2=egOrgSelector

To test
-------
[1] Open the MARC Tag Tables admin interface in the web
    staff client and edit an existing entry. Note that
    changing the selected OU will result in there being
    no change and error messages appearing in the browser
    JavaScript console.
[2] Apply the patch and repeat step 1.
[3] Verify that no errors are logged.

Signed-off-by: Galen Charlton <gmc@equinoxinitiative.org>
Signed-off-by: Chris Sharp <csharp@georgialibraries.org>
Signed-off-by: Bill Erickson <berickxx@gmail.com>