LP#1731496 Avoid PhantomJS BroadcastChannel failure
Avoid attempts to create BroadcastChannel objects in contexts where the
object does not exist.  Specifically, allow PhantomJS to run unit tesst
without dying on:

ReferenceError: Can't find variable: BroadcastChannel

Signed-off-by: Bill Erickson <berickxx@gmail.com>
Signed-off-by: Chris Sharp <csharp@georgialibraries.org>