LP#1485374: Add missing comma on line 667 of oils_auth.c.
Fixes the following compiler error:
oils_auth.c: In function ‘oilsAuthComplete’:
oils_auth.c:668:9: error: expected ‘)’ before string constant
         "open-ils.auth_internal",
         ^

Signed-off-by: Jason Stephenson <jason@sigio.com>
Signed-off-by: Kathy Lussier <klussier@masslnc.org>