LP2116978: resolve angular unit test runtime error
After LP2111731 was merged, running the Angular unit tests
in an environment with the file /openils/lib/javascript/opensrf_ws.js
caused a runtime error:

ReferenceError: OpenSRF is not defined
@/openils/lib/javascript/opensrf_ws.js:20:1

None of our Angular unit tests rely on opensrf_ws.js being in place,
so it's safe to remove it from the test runner setup routine, which
resolves this error.

Release-note: Resolve an error when running Angular unit tests.

To test:
1. Install Evergreen
2. Install Chrome and Firefox
3. Run the Angular unit tests with `npm run test` from the `eg2`
   directory.
4. Confirm that you don't get the error above.

Signed-off-by: Jane Sandberg <sandbergja@gmail.com>
Signed-off-by: Stephanie Leary <stephanie.leary@equinoxoli.org>