LP#2137020: fix quoting issue that can break certain in-query PCRUD permission checks
This patch ensures that PCRUD queries that include WHERE clauses that
include permission.usr_has_object_perm() will quote the table alias
and column name for the fourth parameter of that stored procedure. This
fixes a bug that can cause such queries to fail for tables whose IDL
class name happens to be a reserved word in SQL.

To test
-------
[1] Go to the Local Adminstration interface for item statistical
    categories. Note that it will complain that there is an error
    retrieving results, and the PostgreSQL log will have an error
    like this:

    ERROR: syntax error at or near "asc"
    LINE 1: ...usr_has_object_perm(666, 'STAFF_LOGIN', 'asc', asc.id::TE...

[2] Apply the patch and repeat step 1. This time, the query should
    succeed and the interface return a list of any item statistical
    categories owned by the OUs specified by the interface's
    selector.

Release-note: Fix issue that can cause the "Statistical Categories - Item"
administrative interface to not return results.

Signed-off-by: Galen Charlton <gmc@equinoxOLI.org>
Signed-off-by: Martha Driscoll <driscoll@noblenet.org>
Signed-off-by: Steven Mayo <smayo@georgialibraries.org>
Signed-off-by: Michele Morgan <mmorgan@noblenet.org>