Revert "LP#1851884: eg-fm-record-editor: avoid fetching all rows from linked table"
This reverts commit f2824b8457fa1e941053cdc7fa715ab21e6f58c9.

It causes the following error when building Angular:

    ERROR in src/app/share/fm-editor/fm-editor.component.ts:517:30 - error TS2339: Property 'linkedSearchConditions' does not exist on type 'FmFieldOptions'.

    517             if (fieldOptions.linkedSearchConditions) {
                                     ~~~~~~~~~~~~~~~~~~~~~~
    src/app/share/fm-editor/fm-editor.component.ts:518:51 - error TS2339: Property 'linkedSearchConditions' does not exist on type 'FmFieldOptions'.

    518                 field.idlBaseQuery = fieldOptions.linkedSearchConditions;

There does not appear to be any way to resolve this as the patch also
relies on other changes in rel_3_8 and rel_3_9 that are not present in
rel_3_7.  For these reasons, I am reverting the patch from rel_3_7.

Signed-off-by: Jason Stephenson <jason@sigio.com>